"$schema" = 'https://starship.rs/config-schema.json'


format = """
$directory\
$git_branch\
$git_status\
$fill\
$python\
$lua\
$nodejs\
$golang\
$aws\
$docker_context\
$jobs\
$cmd_duration\
$line_break\
$character"""

add_newline = true
palette = "minicode"


# --- palette ---------------------------------------------------------------
[palettes.minicode]
  bg_base = '#1e1e1e'
  bg_alt = '#262626'
  bg_float = '#323232'

  tan_50 = '#ddd9d5'
  tan_100 = '#D6C1A9'
  tan_200 = '#c5a785'
  tan_400 = '#b58e63'
  tan_600 = '#ac8252'
  tan_700 = '#9b754a'
  tan_800 = '#896842'
  tan_900 = '#785b39'

  muted = '#5e5a55'
  faded = '#383532'
  error = '#941919'
  warn = '#916d00'
  success = '#737300'
  info = '#6b7a78'


# --- modules ---------------------------------------------------------------
[fill]
style = "fg:muted"

[directory]
style = "bold fg:tan_100"
format = "[$path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
truncate_to_repo = false

[directory.substitutions]
"Documents" = "󰈙"
"Downloads" = " "
"Music"     = " "
"Pictures"  = " "

[git_branch]
style = "fg:tan_400"
symbol = " "
format = "[on](fg:tan_50) [$symbol$branch ]($style)"

[git_status]
style = "fg:tan_200"
format = "([$all_status$ahead_behind]($style) )"

[python]
style = "fg:tan_200"
symbol = " "
format = "[${symbol}${pyenv_prefix}(${version} )(\\[$virtualenv\\] )]($style)"
pyenv_version_name = true
pyenv_prefix = ""

[lua]
style = "fg:tan_400"
symbol = " "
format = "[$symbol]($style) "

[nodejs]
style = "fg:tan_200"
symbol = " "
format = "[$symbol]($style) "

[golang]
style = "fg:tan_200"
symbol = " "
format = "[$symbol]($style) "

[aws]
symbol = " "
style = "fg:warn"
format = "[$symbol($profile )(\\[$duration\\] )]($style)"

[docker_context]
symbol = " "
style = "fg:info"
format = "[$symbol]($style) $path"
detect_files = ["docker-compose.yml", "docker-compose.yaml", "Dockerfile"]
detect_extensions = ["Dockerfile"]

[jobs]
symbol = " "
style = "fg:tan_400"
number_threshold = 1
format = "[$symbol]($style)"

[cmd_duration]
min_time = 500
style = "fg:muted"
format = "[$duration]($style)"

[character]
success_symbol = "[❯](fg:tan_400)"
error_symbol   = "[❯](fg:error)"

