"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory\
$git_branch\
$git_status\
$fill\
$python\
$lua\
$nodejs\
$golang\
$aws\
$docker_context\
$jobs\
$cmd_duration\
$line_break\
$character"""

add_newline = true
palette = "tokyonight"


# --- palette ---------------------------------------------------------------
[palettes.tokyonight]
  bg_base   = '#1a1b26'
  bg_dark   = '#16161e'
  bg_hl     = '#292e42'
  terminal  = '#414868'

  fg        = '#c0caf5'
  fg_dark   = '#a9b1d6'
  muted     = '#565f89'

  blue      = '#7aa2f7'
  cyan      = '#7dcfff'
  teal      = '#73daca'
  green     = '#9ece6a'
  magenta   = '#bb9af7'
  orange    = '#ff9e64'
  red       = '#f7768e'
  yellow    = '#e0af68'


# --- modules ---------------------------------------------------------------
[fill]
style = "fg:terminal"

[directory]
style = "bold fg:bg_base bg:magenta"
format = "[  $path ]($style)[\ue0bc](fg:magenta bg:bg_base)"
truncation_length = 3
truncation_symbol = "…/"
truncate_to_repo = false

[directory.substitutions]
"Documents" = "󰈙"
"Downloads" = " "
"Music"     = " "
"Pictures"  = " "

[git_branch]
style = "bold fg:bg_base bg:blue"
symbol = " "
format = "[\ue0ba](fg:blue bg:bg_base)[ $symbol$branch ]($style)[\ue0bc](fg:blue bg:bg_base) "

[git_status]
style = "fg:orange"
format = "([$all_status$ahead_behind]($style) )"

[python]
style = "fg:yellow"
symbol = " "
format = "[${symbol}${pyenv_prefix}(${version} )(\\[$virtualenv\\] )]($style)"
pyenv_version_name = true
pyenv_prefix = ""

[lua]
style = "fg:blue"
symbol = " "
format = "[$symbol]($style) "

[nodejs]
style = "fg:green"
symbol = " "
format = "[$symbol]($style) "

[golang]
style = "fg:cyan"
symbol = " "
format = "[$symbol]($style) "

[aws]
symbol = " "
style = "fg:orange"
format = "[$symbol($profile )(\\[$duration\\] )]($style)"

[docker_context]
symbol = " "
style = "fg:cyan"
format = "[$symbol]($style) $path"
detect_files = ["docker-compose.yml", "docker-compose.yaml", "Dockerfile"]
detect_extensions = ["Dockerfile"]

[jobs]
symbol = " "
style = "fg:magenta"
number_threshold = 1
format = "[$symbol]($style)"

[cmd_duration]
min_time = 500
style = "fg:muted"
format = "[ $duration]($style)"

[character]
success_symbol = "[❯](bold fg:magenta)"
error_symbol   = "[❯](bold fg:red)"
