;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;     ______      __
;    / ________  / ____  __________
;   / /   / __ \/ / __ \/ ___/ ___/
;  / /___/ /_/ / / /_/ / /  (__  )
;  \____/\____/_/\____/_/  /____/
;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;Tokyo Night

[colors]
 bg =  #D91a1b26
 tp= #001a1b26
 trans = #FF00000
 fg =  #c0caf5
 white = #FFFFFF
 fg-alt =  #565f89
 blue-s =  #73daca
; blue = #3d59a1
 blue = #7aa2f7
 blue-alt = #7dcfff
 red =  #f7768e
 green = #9ece6a
 yellow = #e0af68
 cyan = #7dcfff
 magenta = #bb9af7
 orange = #ff9e64
